### PR TITLE
Update report-fig1-percent.Rmd

### PR DESCRIPTION
**Pull request by seabbs**
Slight edits. Not sure I follow the interpretation of effect sizes.

My interpretation is something like: 

There was clear evidence of a reduction in Rt linked with the firebreak in NI across all data streams and methods with a comparable effect size (quote effect size if being fancy) in all sources excepting cases where the evidence of an effect was slightly weaker. In Wales there was reduced evidence for an effect with some evidence in admissions (effect size) and cases (effect size) though in both these data sources the lower 50% credible interval of the effect size was less than 0. There was no evidence of an effect on deaths.

In general, the approach using breakpoints only on known intervention dates and the approach that allowed weekly change outside of known intervention dates produced comparable results. Although, the more flexible approach did in general produce slightly reduced effect sizes with reduced credible intervals.

### CODE REVIEW

**Comment by kathsherratt** [comment]
Thanks @seabbs . I have added this text in to the results (lightly edited) - see what you think. This is then probably one for review by @sbfnk .

**Comment by sbfnk** [comment]
In Wales, could it be that the estimated effect size in Fig. 1 is with respect to the second break point? If not I struggle to reconcile this with the R trajectories which show a step change at the first break point.

**Comment by seabbs** [comment]
Ah yes - didn't look at the timeseries. That does make sense. Interpretation -> drain.

**Comment by kathsherratt** [comment]
I'm so sorry - you are right Seb, Wales had the post-firebreak effect sizes as I got the strata wrong. 

I have fixed this and updated.

Northern Ireland wasn't affected by this mistake so have basically kept that interpretation, but updated the text for Wales.

**Comment by seabbs** [comment]
Looks really good - I added a few bits and bobs feel free to edit or roll back.

**Comment by sbfnk** [comment]
All looking good - thanks!

**Pull request merged**
